\mainmatter


# Stadium Roof

Estimate the hearing/cooling requirements for adding a roof to an outdoor stadium. I've described the stadium in terms of Bryant-Denny, but any stadium would do. Model the stadium as a sphere that would reasonably approximate the interior volume of your proposed structure. For reference, the Superdome encloses about 3,500,000 m3.  

You have two worst case scenarios to consider. 


## Summer Day

Set the outside temperature to be the hottest day of the year for the stadium location. Fill it to seating capacity. This will be a standard refrigeration (air conditioning) system like in your text. You need to account for the following:

1. Heat generated by the occupants  
1. Heat transfer in through the roof (top hemisphere). See #3 below.  
1. solar irradiation (hottest day)   
1. conduction/convection with outside   
1. Adiabatic lower hemisphere   

## Winter Night

Set the outside temperature to be the coldest night of the year for the stadium location. Choose natural gas heating or a heat pump with COPHP = 1 + COPR of the Summer Day AC system. Assume the following:

1. No occupants    
1. No solar irradiation.    
1. Adiabatic lower hemisphere    
1. Heat transfer out through the roof. See #3 below.   


## Calculations
Determine the energy required to maintain a steady comfortable indoor temperature (20 °C) for both scenarios. For context, calculate the energy cost ($/hour). Use the local cost of energy, discounted 20%.

Using the heating and cooling systems from (1), determine the time it takes to reach the comfort temperature when starting from an unoccupied arena at the outdoor temperature (ie, a huge volume of air).

Compare the heating cost to electric heating, which is often used in cheap apartments blocks. In electric heating, electricity is converted directly to heat ( = 100%!). 

## Useful Information

A reasonable COP for an arena-scale air-conditioning system is COP = 3 - 3.5.
Solar irradiation for your location can be found in an online almanac or from NOAA or DOE. It’ll be a heat flux in units of W/m2. The roof will reflect a portion of this energy. A good source for solar reflectance values (they range from 0-1) for roof coatings can be found at the Cool Roofs Ratings Council (https://coolroofs.org/directory/results). Apply this heat flux to the entire roof area. 
Estimate the thermal conductivity of your roof at 0.3 W/K. Heat flux (power/area) is expressed as


\begin{align}
 q'' &= -k \frac{\text dT}{\text dx} \\
 \text{where}\hfill \notag \\
 q'' &\equiv \text{heat flux} \left[ \frac{W}{m^2} \right]  \notag \\
 k &\equiv \text{thermal conductivity} \left[ \frac{W}{m K} \right]  \notag 
\end{align}


where k is thermal conductivity.
The attached Building Energy Auditing Module has extensive information on the thermodynamics and heat transfer of building energy systems. It has a ton of information germane to this project, though most of it is overkill. 
